### PR TITLE
Support, test target derivatives for direct evaluation

### PR DESCRIPTION
**Pull request by inducer**
cc @alexfikl

### CODE REVIEW

**Comment by alexfikl** [comment]
Thanks for fixing this!

Should the same chunk be added to the matrix evaluation? All of that is direct too.

**Comment by inducer** [comment]
Yeah! (Is there a way that they could share that code?)

**Comment by alexfikl** [comment]
> Yeah! (Is there a way that they could share that code?)

Maybe add a memoized `get_expansion_for_target_kernels` (or something?) with this logic to `QBXLayerPotential` so that the matrix code can just call that?

**Comment by inducer** [comment]
That sounds good. `get_expansion_for_qbx_direct_eval` maybe? Feel free to push that to this PR if you like.

**Comment by inducer** [comment]
Closing in favor of #79.

**Comment by inducer** [comment]
Btw you're right: CI for this did eventually fail. :)

**Comment by alexfikl** [comment]
> Btw you're right: CI for this did eventually fail. :)

I'm surprised this didn't already fail in inducer/sumpy#47 though. Was it not using the updated code for some reason?

**Pull request closed without merging**
