### PR TITLE
GitHub ci examples

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by isuruf** [comment]
Examples run passed, but pytest runs with sympy failed. :cry:

**Comment by inducer** [comment]
Ugh.

Comparing the Linux run from the failure of cf6f6a1 (`bad`) with the Linux run from [this successful run](https://github.com/inducer/pytential/runs/1646019768) (`good`) gives quite a few package differences:

```diff
--- good	2021-01-11 21:53:01.191682535 -0600
+++ bad	2021-01-11 21:53:14.263704055 -0600
@@ -981,9 +1008,9 @@
 appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
 c-ares                    1.17.1               h36c2ea0_0    conda-forge
 ca-certificates           2020.12.5            ha878542_0    conda-forge
-certifi                   2020.12.5        py38h578d9bd_0    conda-forge
+certifi                   2020.12.5        py38h578d9bd_1    conda-forge
 curl                      7.71.1               he644dc0_8    conda-forge
-cython                    0.29.21          py38h348cfbe_1    conda-forge
+cython                    0.29.21          py38h709712a_2    conda-forge
 decorator                 4.4.2                      py_0    conda-forge
 expat                     2.2.9                he1b5a44_2    conda-forge
 fontconfig                2.13.1            h736d332_1003    conda-forge
@@ -998,8 +1025,8 @@
 jpeg                      9d                   h36c2ea0_0    conda-forge
 krb5                      1.17.2               h926e7f8_0    conda-forge
 ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
-libblas                   3.9.0                6_openblas    conda-forge
-libcblas                  3.9.0                6_openblas    conda-forge
+libblas                   3.9.0                7_openblas    conda-forge
+libcblas                  3.9.0                7_openblas    conda-forge
 libclang-cpp10            10.0.1          default_hde54327_1    conda-forge
 libcurl                   7.71.1               hcdd3856_8    conda-forge
 libedit                   3.1.20191231         he28a2e2_2    conda-forge
@@ -1012,7 +1039,7 @@
 libgomp                   9.3.0               h5dbcf3e_17    conda-forge
 libhwloc                  2.4.0                h6746aa3_0    conda-forge
 libiconv                  1.16                 h516909a_0    conda-forge
-liblapack                 3.9.0                6_openblas    conda-forge
+liblapack                 3.9.0                7_openblas    conda-forge
 libllvm10                 10.0.1               he513fc3_3    conda-forge
 libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
 libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
@@ -1020,15 +1047,15 @@
 libssh2                   1.9.0                hab1572f_5    conda-forge
 libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
 libuuid                   2.32.1            h7f98852_1000    conda-forge
-libxcb                    1.13              h14c3975_1002    conda-forge
+libxcb                    1.13              h7f98852_1003    conda-forge
 libxml2                   2.9.10               h72842e0_3    conda-forge
 mako                      1.1.3              pyh9f0ad1d_0    conda-forge
-markupsafe                1.1.1            py38h8df0ef7_2    conda-forge
+markupsafe                1.1.1            py38h497a2fe_3    conda-forge
 mpc                       1.1.0             h04dde30_1009    conda-forge
 mpfr                      4.0.2                he80fd80_1    conda-forge
 mpmath                    1.1.0                      py_0    conda-forge
 ncurses                   6.2                  h58526e2_4    conda-forge
-numpy                     1.19.4           py38h18fd61f_2    conda-forge
+numpy                     1.19.5           py38h18fd61f_1    conda-forge
 occt                      7.4.0                h9121d39_3    conda-forge
 ocl-icd                   2.2.14               h7f98852_0    conda-forge
 openssl                   1.1.1i               h7f98852_0    conda-forge
@@ -1041,70 +1068,70 @@
 pyopencl                  2020.3.1         py38hf6732f7_0    conda-forge
 python                    3.8.6           hffdb5ce_4_cpython    conda-forge
 python_abi                3.8                      1_cp38    conda-forge
-pytools                   2020.4.4           pyhd3deb0d_0    conda-forge
+pytools                   2021.1             pyhd3deb0d_0    conda-forge
 readline                  8.0                  he28a2e2_2    conda-forge
 scipy                     1.6.0            py38hb2138dd_0    conda-forge
-setuptools                49.6.0           py38h924ce5b_2    conda-forge
+setuptools                49.6.0           py38h578d9bd_3    conda-forge
 six                       1.15.0             pyh9f0ad1d_0    conda-forge
 sqlite                    3.34.0               h74cdb3f_0    conda-forge
 sympy                     1.5.1            py38h32f6830_2    conda-forge
-tbb                       2020.2               h4bd325d_2    conda-forge
+tbb                       2020.2               h4bd325d_3    conda-forge
 tk                        8.6.10               h21135ba_1    conda-forge
 tzdata                    2020f                he74cb21_0    conda-forge
 wheel                     0.36.2             pyhd3deb0d_0    conda-forge
 xorg-fixesproto           5.0               h14c3975_1002    conda-forge
-xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
+xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
 xorg-libice               1.0.10               h516909a_0    conda-forge
 xorg-libsm                1.2.3             h84519dc_1000    conda-forge
 xorg-libx11               1.6.12               h516909a_0    conda-forge
-xorg-libxau               1.0.9                h14c3975_0    conda-forge
-xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
+xorg-libxau               1.0.9                h7f98852_0    conda-forge
+xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
 xorg-libxext              1.3.4                h516909a_0    conda-forge
 xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
 xorg-libxmu               1.1.3                h516909a_0    conda-forge
 xorg-libxrender           0.9.10            h516909a_1002    conda-forge
 xorg-libxt                1.1.5             h516909a_1003    conda-forge
 xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
-xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
+xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
 xorg-xproto               7.0.31            h7f98852_1007    conda-forge
 xz                        5.2.5                h516909a_1    conda-forge
 zlib                      1.2.11            h516909a_1010    conda-forge
```

**Comment by inducer** [comment]
It's also suspicious that the Mac and Linux runs failed in exactly the same ways.

**Comment by inducer** [comment]
Trying with numpy pinned in #48.

**Comment by inducer** [comment]
Any guesses why symengine succeeds and sympy doesn't?

**Comment by inducer** [comment]
Also, we're running with sympy pinned to a version that's old as dirt: https://github.com/inducer/pymbolic/blob/ca9dcc5befe13b7a29fdfbc21ec687a23398b2ec/pymbolic/primitives.py#L633-L643

**Comment by inducer** [comment]
To try removing the sympy pin: #49.

**Comment by inducer** [comment]
That doesn't seem to have been it either.

**Comment by inducer** [comment]
#50 to try whether  https://github.com/inducer/loopy/pull/186 makes a difference.

**Comment by kaushikcfd** [comment]
The error is loopy is inferring `pi` in  `3.141592653589793**(-1)` to be of type f32.
The generated code therefore has terms like: `loopy_pow_float32_int32(3.141592653589793, -1.0);`.

We should correct [this line](https://github.com/inducer/loopy/blob/c2ca207a782156f4cb591eca1dc93687caa08caa/loopy/type_inference.py#L218-L220).

**Comment by inducer** [comment]
@kaushikcfd Thanks for investigating so quickly! See https://github.com/inducer/loopy/pull/189 for a proposed fix, and #51 for a test of that against pytential.

**Pull request merged**
