### PR TITLE
Reduce deprecation warnings

### PR DESCRIPTION
**Pull request by alexfikl**
https://github.com/inducer/pytential/actions/runs/5314367888/jobs/9621723155 had 1701079 warnings, which seems excessive, so this tries to reduce them a bit.

### CODE REVIEW

**Comment by inducer** [comment]
LGTM, thanks!

**Comment by alexfikl** [comment]
> LGTM, thanks!

This gets it down to about 13000 warnings, which seems a bit more manageable!

**Comment by inducer** [comment]
I mean, that's still a crazy number... but :tada: progress!

**Comment by alexfikl** [comment]
> I mean, that's still a crazy number... but tada progress!

Another ~2k should go away once inducer/pyopencl#689 gets into a release, but the rest are from `TaggableCLArray`, so those will have to wait a while :(

**Comment by inducer** [comment]
https://github.com/inducer/pyopencl/releases/tag/v2023.1.1. Should be on pypi once https://github.com/inducer/pyopencl/actions/runs/5371394328 completes.

**Pull request merged**
