### PR TITLE
Bump to Python 3.8

### PR DESCRIPTION
**Pull request by alexfikl**
This also cleaned up the CI to use
```
curl -L -O https://tiker.net/ci-support-v0
```

The Gitlab CI is also passing nicely at
https://gitlab.tiker.net/fikl2/pytential/-/pipelines/345017

### CODE REVIEW

**Comment by alexfikl** [comment]
Not sure if this this is a good time to bump the version, so feel free to wait on it. I just noticed `modepy` got bumped in inducer/modepy#59 and thought to go ahead :grin:

**Comment by inducer** [comment]
LGTM, thanks! This has very little potential to conflict with stuff, so I don't see a good reason not to just go for it.

**Comment by inducer** [comment]
On a related note, I noticed that
```
pyupgrade --py38-plus
```
doesn't seem to do an awful lot. On Pytential, it only gave me some f-strings and `tuple([list compr])` $\to$ `tuple(gen expr)`. Is that your experience, too?

**Comment by alexfikl** [comment]
> Is that your experience, too?

Yep, I tried it too and didn't think it was worth it.

**Pull request merged**
