### PR TITLE
ci: bump action versions

### PR DESCRIPTION
**Pull request by alexfikl**
Noticed `meshmode` bumped them the other day, so went ahead and bumped them here too.

Is it worth adding a `dependabot` or something to bump these automatically?

### CODE REVIEW

**Comment by inducer** [comment]
> Is it worth adding a dependabot or something to bump these automatically?

I'd like to? But I don't know how.

**Comment by inducer** [comment]
Thanks!

**Comment by alexfikl** [comment]
> I'd like to? But I don't know how.

Should be in `Settings > Code security & analysis -> Dependabot version updates` from what I remember. That adds a little file that should contain something like this:
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions

**Comment by inducer** [comment]
Tada: https://github.com/inducer/pytential/commit/a2f4c979610dc6caf6fd9ed1bb6800af96052322

(Now to do it for the other umpteen things, ugh.)

**Comment by alexfikl** [comment]
> Tada: [a2f4c97](https://github.com/inducer/pytential/commit/a2f4c979610dc6caf6fd9ed1bb6800af96052322)
> 
> (Now to do it for the other umpteen things, ugh.)

@inducer Woohoo! I'm happy to help with a few repos if you want. I'm not sure if it actually needs something in the repo settings or just adding the file enough to trigger it?

**Pull request merged**
