### PR TITLE
Add a NodeMin reduction

### PR DESCRIPTION
**Pull request by alexfikl**

### CODE REVIEW

**Comment by inducer** [comment]
Add a test? :)

**Comment by inducer** [comment]
Also, thanks for working on this!

**Comment by inducer** [comment]
(Looks good otherwise.)

**Comment by alexfikl** [comment]
> Add a test? :)

Added a test case for all the `NodeSomething` in eb1752d.

**Comment by inducer** [comment]
LGTM. Thanks for working on this!

**Pull request merged**
